<?php

namespace Database\Seeders;

use App\Models\Pendaftar;
use Illuminate\Database\Seeder;

class PendaftarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pendaftars = [
            // Data 1 - Status Diterima dengan Wali
            [
                'gelombang_id' => 1,
                'nomor_pendaftaran' => 'PPDB2024-001',
                'jurusan' => 'Teknik Komputer dan Jaringan',
                'nama_lengkap' => 'Ahmad Zainudin',
                'no_hp' => '081234567890',
                'email' => 'ahmad.zainudin@gmail.com',
                'jkel' => 'L',
                'gol_darah' => 'A',
                'nik' => '3319012005080001',
                'tempat_lahir' => 'Pati',
                'tanggal_lahir' => '2008-05-20',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Pati',
                'kecamatan' => 'Margoyoso',
                'desa' => 'Kajen',
                'dusun' => 'Krajan',
                'alamat' => 'Jl. Raya Kajen No. 123',
                'rt' => '002',
                'rw' => '003',
                'kodepos' => '59154',
                'asalsekolah' => 'SMP Negeri 1 Margoyoso',
                'nisn' => '0087654321',
                'rekomendasi' => 'Kepala Sekolah SMP N 1 Margoyoso',
                'nama_ayah' => 'Bapak Sutrisno',
                'pekerjaan_ayah' => 'Petani',
                'pendidikan_ayah' => 'SMA',
                'nama_ibu' => 'Ibu Siti Aminah',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'pendidikan_ibu' => 'SMP',
                'nama_wali' => 'Bapak Hasan Basri',
                'pekerjaan_wali' => 'Wiraswasta',
                'pendidikan_wali' => 'S1',
                'telp_wali' => '081298765432',
                'foto' => 'foto-ahmad.jpg',
                'kk' => 'kk-ahmad.jpg',
                'ktp_ortu' => 'ktp-ortu-ahmad.jpg',
                'aktalahir' => 'akta-ahmad.jpg',
                'kip' => 'kip-ahmad.jpg',
                'pkh' => null,
                'kks' => null,
                'status' => 'diterima',
                'created_at' => now()->subDays(15),
                'updated_at' => now()->subDays(10),
            ],

            // Data 2 - Status Diproses tanpa Wali
            [
                'gelombang_id' => 1,
                'nomor_pendaftaran' => 'PPDB2024-002',
                'jurusan' => 'Rekayasa Perangkat Lunak',
                'nama_lengkap' => 'Siti Nur Azizah',
                'no_hp' => '082345678901',
                'email' => 'siti.azizah@gmail.com',
                'jkel' => 'P',
                'gol_darah' => 'B',
                'nik' => '3319015006080002',
                'tempat_lahir' => 'Pati',
                'tanggal_lahir' => '2008-06-15',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Pati',
                'kecamatan' => 'Margoyoso',
                'desa' => 'Kajen',
                'dusun' => 'Pesantren',
                'alamat' => 'Jl. Pesantren No. 45',
                'rt' => '001',
                'rw' => '002',
                'kodepos' => '59154',
                'asalsekolah' => 'SMP Negeri 2 Margoyoso',
                'nisn' => '0087654322',
                'rekomendasi' => 'Kepala Sekolah SMP N 2 Margoyoso',
                'nama_ayah' => 'Bapak Ahmad Fauzi',
                'pekerjaan_ayah' => 'PNS',
                'pendidikan_ayah' => 'S1',
                'nama_ibu' => 'Ibu Kholifah',
                'pekerjaan_ibu' => 'Guru',
                'pendidikan_ibu' => 'S1',
                'nama_wali' => '',
                'pekerjaan_wali' => '',
                'pendidikan_wali' => '',
                'telp_wali' => '',
                'foto' => 'foto-siti.jpg',
                'kk' => 'kk-siti.jpg',
                'ktp_ortu' => 'ktp-ortu-siti.jpg',
                'aktalahir' => 'akta-siti.jpg',
                'kip' => null,
                'pkh' => 'pkh-siti.jpg',
                'kks' => 'kks-siti.jpg',
                'status' => 'diproses',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],

            // Data 3 - Status Ditolak dengan Wali
            [
                'gelombang_id' => 1,
                'nomor_pendaftaran' => 'PPDB2024-003',
                'jurusan' => 'Teknik Kendaraan Ringan',
                'nama_lengkap' => 'Muhammad Ridwan',
                'no_hp' => '083456789012',
                'email' => 'ridwan.muhammad@gmail.com',
                'jkel' => 'L',
                'gol_darah' => 'O',
                'nik' => '3319011007080003',
                'tempat_lahir' => 'Kudus',
                'tanggal_lahir' => '2008-07-10',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Pati',
                'kecamatan' => 'Margoyoso',
                'desa' => 'Tanjungsari',
                'dusun' => 'Ngemplak',
                'alamat' => 'Jl. Mawar No. 78',
                'rt' => '003',
                'rw' => '005',
                'kodepos' => '59154',
                'asalsekolah' => 'SMP Islam Kajen',
                'nisn' => '0087654323',
                'rekomendasi' => 'Kepala Sekolah SMP Islam Kajen',
                'nama_ayah' => 'Bapak Mahmud',
                'pekerjaan_ayah' => 'Buruh',
                'pendidikan_ayah' => 'SD',
                'nama_ibu' => 'Ibu Fatimah',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'pendidikan_ibu' => 'SD',
                'nama_wali' => 'Bapak Mustofa',
                'pekerjaan_wali' => 'Pedagang',
                'pendidikan_wali' => 'SMA',
                'telp_wali' => '081287654321',
                'foto' => 'foto-ridwan.jpg',
                'kk' => 'kk-ridwan.jpg',
                'ktp_ortu' => 'ktp-ortu-ridwan.jpg',
                'aktalahir' => 'akta-ridwan.jpg',
                'kip' => 'kip-ridwan.jpg',
                'pkh' => 'pkh-ridwan.jpg',
                'kks' => null,
                'status' => 'ditolak',
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(18),
            ],

            // Data 4 - Status Diterima tanpa Wali
            [
                'gelombang_id' => 1,
                'nomor_pendaftaran' => 'PPDB2024-004',
                'jurusan' => 'Teknik Komputer dan Jaringan',
                'nama_lengkap' => 'Dewi Nur Laila',
                'no_hp' => '084567890123',
                'email' => 'dewi.laila@gmail.com',
                'jkel' => 'P',
                'gol_darah' => 'AB',
                'nik' => '3319015508080004',
                'tempat_lahir' => 'Pati',
                'tanggal_lahir' => '2008-08-25',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Pati',
                'kecamatan' => 'Margoyoso',
                'desa' => 'Kajen',
                'dusun' => 'Kalibening',
                'alamat' => 'Jl. Kalibening Raya No. 56',
                'rt' => '004',
                'rw' => '006',
                'kodepos' => '59154',
                'asalsekolah' => 'SMP Negeri 3 Margoyoso',
                'nisn' => '0087654324',
                'rekomendasi' => 'Kepala Sekolah SMP N 3 Margoyoso',
                'nama_ayah' => 'Bapak Bambang Sutopo',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pendidikan_ayah' => 'SMA',
                'nama_ibu' => 'Ibu Endang Sri Lestari',
                'pekerjaan_ibu' => 'Pedagang',
                'pendidikan_ibu' => 'SMA',
                'nama_wali' => '',
                'pekerjaan_wali' => '',
                'pendidikan_wali' => '',
                'telp_wali' => '',
                'foto' => 'foto-dewi.jpg',
                'kk' => 'kk-dewi.jpg',
                'ktp_ortu' => 'ktp-ortu-dewi.jpg',
                'aktalahir' => 'akta-dewi.jpg',
                'kip' => null,
                'pkh' => null,
                'kks' => null,
                'status' => 'diterima',
                'created_at' => now()->subDays(12),
                'updated_at' => now()->subDays(8),
            ],

            // Data 5 - Status Diproses dengan Wali
            [
                'gelombang_id' => 2,
                'nomor_pendaftaran' => 'PPDB2024-005',
                'jurusan' => 'Rekayasa Perangkat Lunak',
                'nama_lengkap' => 'Fahmi Hidayat',
                'no_hp' => '085678901234',
                'email' => 'fahmi.hidayat@gmail.com',
                'jkel' => 'L',
                'gol_darah' => '-',
                'nik' => '3319012009080005',
                'tempat_lahir' => 'Jepara',
                'tanggal_lahir' => '2008-09-20',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Pati',
                'kecamatan' => 'Margoyoso',
                'desa' => 'Plangitan',
                'dusun' => 'Krajan',
                'alamat' => 'Jl. Ahmad Yani No. 89',
                'rt' => '005',
                'rw' => '007',
                'kodepos' => '59154',
                'asalsekolah' => 'SMP Muhammadiyah Pati',
                'nisn' => '0087654325',
                'rekomendasi' => 'Kepala Sekolah SMP Muhammadiyah',
                'nama_ayah' => 'Bapak Nur Kholis',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'pendidikan_ayah' => 'D3',
                'nama_ibu' => 'Ibu Umi Salamah',
                'pekerjaan_ibu' => 'Karyawan Swasta',
                'pendidikan_ibu' => 'D3',
                'nama_wali' => 'Bapak Abdullah',
                'pekerjaan_wali' => 'PNS',
                'pendidikan_wali' => 'S2',
                'telp_wali' => '081276543210',
                'foto' => 'foto-fahmi.jpg',
                'kk' => 'kk-fahmi.jpg',
                'ktp_ortu' => 'ktp-ortu-fahmi.jpg',
                'aktalahir' => 'akta-fahmi.jpg',
                'kip' => null,
                'pkh' => null,
                'kks' => null,
                'status' => 'diproses',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
        ];

        foreach ($pendaftars as $pendaftar) {
            Pendaftar::create($pendaftar);
        }
    }
}
